### ISSUE TITLE
Slower performance than the notebook?

### ISSUE THREAD

**Issue by atyshka** [cagbal/ros_people_object_detection_tensorflow#42]
Just wondering, do you have any idea why the runtimes for the detections in this node are about double the detection times in the jupyter notebook it's based off of? I get about 50ms in the notebook and 100ms in this repo. The code is copied almost verbatim, so I can't see why there is an issue. Can you reproduce this issue?

**Comment by cagbal** [comment]
Hmm. nice point! I am also getting around 100ms. I did not test the notebook code's time, though. 

Currently, I cannot reach my computer but I will try it and let you know. Btw, did you disable all other notes? 

Could you try just launching this cob_people_object_detection_tensorflow.launch?

Otherwise, I will try it nearly in 1 week.

**Comment by atyshka** [comment]
Yeah I’m only using the detection node. I’m using Jetson Xavier which might perform differently, I just though it was strange that this code took double the time when it’s basically the same as the notebook code. Wondering if it’s reproducible on your system.

**Comment by cagbal** [comment]
Ok let's try for 10 imgs. I'll let you know.

**Comment by cagbal** [comment]
Here is the result:

> 2.6096081733703613
> 2.943655252456665
> 2.531284809112549
> 2.513815402984619
> 2.484112024307251
> 2.609175205230713
> 2.50939679145813
> 2.451589584350586
> 2.4029273986816406
> 2.3995888233184814
